### ISSUE TITLE
Revert naming of `ShellJob` to `ShellTask`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-workgraph#118]
Recently, the name of the identifier for running shell commands via `aiida-shell` in `WorkGraph` has been renamed from `ShellJob` to `ShellTask`. While I understand where the motivation comes from (as part of the general rename from `Node` to `Task`), I don't think this is a good idea. It introduces inconsistencies, e.g. with `verdi process list`, as the actual entities that are submitted are still `ShellJob`s. This class name is defined inside `aiida-shell` and likely won't change. Furthemore, I don't think there is any need for the rename from `ShellJob` to `ShellTask` (the previous name didn't contain `Node` anyway).

**Comment by superstar54** [comment]
Hi @GeigerJ2 , thanks for the suggestion! I agree.

**Comment by superstar54** [comment]
Same that we need rename "PythonTask" to "PythonJob".

**Comment by GeigerJ2** [comment]
I'd be happy to take care of it to sneak myself into the contributor list of this great tool :D

**Comment by superstar54** [comment]
Great, thanks!

**Comment by GeigerJ2** [comment]
> Same that we need rename "PythonTask" to "PythonJob".

I'm a bit surprised by that. Never heard you call it "PythonTask" (ever :D), and your related issues on the repo from 2 days ago also always refer to it as "PythonJob" ^^

In any case, I also fixed the renaming of that in my `ShellJob` PR #121.
