### ISSUE TITLE
✨ Decorating regular Python functions as `PythonJob` API

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-workgraph#166]
From a recent discussion with @superstar54 and @GeigerJ2: I would like to be able to just decorate a regular Python function and run it as a `PythonJob` inside a `WorkGraph`, e.g.:

```python
from aiida_workgraph import task
from functions import generate_structures. # This is the regular Python function I want to run with AiiDA

decorated_function = task.pythonjob()(generate_structures)

wg = WorkGraph("first_workflow")
wg.tasks.new(decorated_function)
```

Some notes:

* What if the user inputs an AiiDA node type? I.e. the input specified for the structure is an `orm.StructureData`? In this case, what should the variable contain _inside_ the function body execution? If it is a `StructureData`, this will most likely fail. But how do we know what mutable Python type to convert the `StructureData` to? We could (1) read the function signature and see if the type hinting is there, or if not (2) use some configurable default, but this is always somewhat fragile. Ideally there would be a clear bijection between mutable Python types and AiiDA node types, so there is never any confusion on what mutable type to use inside the function body.

**Comment by superstar54** [comment]
> Ideally there would be a clear bijection between mutable Python types and AiiDA node types, so there is never any confusion on what mutable type to use inside the function body.

For the moment, this is how `PythonJob` handles data conversion.
- mutable Python data -> AiiDA Data, WorkGraph will search in the `aiida.data` entry point. If not found, use Pickle. If multiple entry points are found, it will use the one from the config file. If not found in the config file, raise an error.
- AiiDA data -> mutable Python data, all the AiiDA data passed to the `PythonJob` should have a `value` attribute, which should return the mutable Python data.
