### ISSUE TITLE
Make `"name"` specifier of `parser_outputs` optional

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-workgraph#167]
From the same discussion as #166 with @mbercx and @superstar54, also came this issue: I'm getting quite confused these days with all the string annotations one needs to correctly set up. They seem a bit cumbersome and repetetive, e.g., having to specify:
```python
parser_outputs=[{"name": "energy"}, {"name": "structure"}, {"name": "forces"}]
```
for using a custom parser when running a `ShellJob`. In this case, I propose we make the `"name"` key optional, and allow users to just specify a list (or, make the argument fully optional and inspect from the parser actual outputs of the parser function, though, that might be just wishful thinking, as it's passed as PickledData). I understand that other options could be specified here, e.g. data type, so we need to find a balance between extensibility and ease of use, so the default could be `"name"`, while other/multiple identifiers can still be used.

There are more places where one has to add such string identifiers, the `"General"` comes to mind, e.g., from here:
```python
SeekpathTask = build_task(
    seekpath_structure_analysis,
    outputs=[["General", "primitive_structure"], ["General", "explicit_kpoints"]],
)
```
where `"General"` could also be the default and users could just provide a simple list, as I think came already up on our first `WorkGraph` coding day

**Comment by superstar54** [comment]
May I ask where do you find the `SeekpathTask` example code?
```
outputs=[["General", "primitive_structure"], ["General", "explicit_kpoints"]],
```
The `General` keyword has been dropped in the latest version.

**Comment by GeigerJ2** [comment]
In principle, it's from the RTD on Transferring WorkChain to WorkGraph, but I just checked, and actually it uses "name", not "General". Might have been an older version I still hadn't updated on my laptop. In any case, then the "General" issue is void if it's dropped 👍🏽
