### ISSUE TITLE
Update `wg.add_task` to `wg.tasks.new` in examples

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-workgraph#171]
Just putting it here for future reference so that we don't forget. The `WorkGraph.add_task` seems to have been replaced by `WorkGraph.tasks.new`. In some places in the docs, e.g. [here](https://aiida-workgraph.readthedocs.io/en/latest/tutorial/eos.html#Visualize-the-workgraph) the old syntax is still being used:
https://github.com/aiidateam/aiida-workgraph/blob/e0c448fd7dde713a76ab407d669032406ba11243/docs/source/tutorial/eos.ipynb#L47-L48

**Comment by superstar54** [comment]
Hi @GeigerJ2 , just to clarify: it's the reverse. It is suggested that users use `add_task`. Even though the `add_task` is call `nodes.new` internally.

@edan-bainglass Strong suggests that we only expose `add_task` to the user, as implemented in #75 .

**Comment by GeigerJ2** [comment]
Ah, I see now why it was giving me an exception. This was just added in commit 50d552a19738a81987117009036299353312b152 from 6 hours. I'm keeping the repo up-to-date, but not _that_ up-to-date :D Then this can be closed.
