### ISSUE TITLE
Colliding filenames for case-insensitive filesystems pythonjob_{parent_folder,shell_command}

### ISSUE THREAD

**Issue by agoscinski** [aiidateam/aiida-workgraph#200]
When I clone the repo I get the following warning
```
warning: the following paths have collided (e.g. case-sensitive paths                                       
on a case-insensitive filesystem) and only one from the same                                                
colliding group is in the working tree:                                                                     
                                                                                                            
  'docs/source/built-in/html/PythonJob_parent_folder.html'                                                  
  'docs/source/built-in/html/pythonjob_parent_folder.html'                                                  
  'docs/source/built-in/html/PythonJob_shell_command.html'                                                  
  'docs/source/built-in/html/pythonjob_shell_command.html'
```
and it leaves me in weird git state where git thinks the file has changed but also thinks that the file does not exist. I checked the files, `pythonjob_parent_folder.html` and `pythonjob_shell_command.html` are not used in the docs an can therefore be removed.  They probably still exist from a renaming of the output html filename.

**Comment by superstar54** [comment]
Yes, there are some unused html files in the docs, also some files have the same names but different cases for the characters. We have to clean it a little bit.
Note all the HTML files insides the `html` folders are generated from the notebooks. The name of the file is the name of the WorkGraph. Sometimes, we change the name of the WorkGraph but forget to delete the old HTML files.
