### ISSUE TITLE
Support latest aiida-shell 0.8.0

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-workgraph#316]
Here is the [release log](https://github.com/sphuber/aiida-shell/commit/c6bbb6145588f9aefc0e61d1db3c3c35a609246b)

- [x] Change the signature of custom parser functions. I think we only need to update the docs, in the section which use parser. When you do this, please also fix #314.
- [x] A new `prepare_shell_job_inputs` function, which will solve #315 

I think we need two PRs to implement theses. @agoscinski , @GeigerJ2 , do you want to work on this? If I am missing something else, please add a comment.

**Comment by GeigerJ2** [comment]
Hi @superstar54, I discussed with @agoscinski and I will take care of both issues. Makes sense also bc I am the culprit who made Seb change the parser signature 😆 Cheers!

**Comment by superstar54** [comment]
Great, thanks!
For the second issue, the idea is to use the `prepare_shell_job_inputs` inside the [prepare_for_shell_task](https://github.com/aiidateam/aiida-workgraph/blob/5bf734af360b12e238ac8955f8eb0512fb19fb29/aiida_workgraph/engine/utils.py#L132-L164) function to prepare inputs for the ShellJob task.

**Comment by superstar54** [comment]
closed by #326
