### ISSUE TITLE
Graph visualization in notebook can fail with javascript error

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-workgraph#59]
This is likely due to outdated dependencies. In our test case I had `jupyter==1.0.0` and `notebook==6.5.4`. After updating to `notebook==7.1.3` the visualization now works. Should figure out if `notebook` is really the critical dependency and if so add this minimal requirement to the dependency requirements

**Comment by superstar54** [comment]
Thanks, @sphuber, for reporting this issue. This is related to the dependecy `anywdiget`, and should be fixed in https://github.com/manzt/anywidget/issues/532
